---
# consul_advertise_addr:      "{{ hostvars[inventory_hostname].consul_advertise_address }}"
consul_datacenter:                  alpha
consul_iface:                       eth1
consul_bind_address:                "{{ hostvars[inventory_hostname].consul_advertise_address }}"
# put this key in ansible-vault and lookup
consul_raw_key:                 ""
consul_bootstrap_expect:            3
consul_version:                     1.1.0

# allow for external ui access
consul_client_address:              0.0.0.0
consul_syslog_enable:               false
consul_node_name:                   "{{ inventory_hostname_short }}"
validate_certs:                     true
ansible_python_interpreter:         /usr/bin/python3

# tls config
# consul_tls_enable:                  true
consul_dnsmasq_enable:              true
# consul_tls_verify_incoming:         true
# consul_tls_verify_outgoing:         true
# consul_tls_verify_server_hostname:  true
# consul_tls_dir:                     /etc/ssl/certs
# consul_tls_ca_crt:                  cacert.pem
# consul_tls_server_crt:              vagrant-hashi-stack.cert
# consul_server_key:                  vagrant-hashi-stack.key

consul_tls_copy_keys:               false
consul_ports_http:                  8500
# consul_ports_http:                  8501
# consul_ports_https:                 8500

# consul_domain:                      consul.local

# relative to roles/brianshumate.consul/tasks/
# consul_tls_src_files:               "../../../config/tls/certs"
# consul_recursors:
#   - 8.8.8.8
#   - 8.8.4.4

# consul_acl_enable:                  true
# consul_acl_datacenter:              alpha
# consul_acl_down_policy:             allow
# consul_acl_default_policy:          allow
# consul_acl_master_token:            fc7e1293-b087-494a-b26f-318c6d79ef32
