---
all:
  vars:
    ansible_host: 127.0.0.1
    ansible_user: vagrant
    ansible_python_interpreter: /usr/bin/python
  hosts:
    vagrant-hashi-stack-1.alpha.consul:
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/vagrant-hashi-stack-1/virtualbox/private_key
      ip_address: 192.168.33.10
    vagrant-hashi-stack-2.alpha.consul:
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/vagrant-hashi-stack-2/virtualbox/private_key
      ip_address: 192.168.33.11
    vagrant-hashi-stack-3.alpha.consul:
      ansible_port: 2201
      ansible_private_key_file: .vagrant/machines/vagrant-hashi-stack-3/virtualbox/private_key
      ip_address: 192.168.33.12
  children:
    consul_instances:
      hosts:
        vagrant-hashi-stack-1.alpha.consul:
          consul_iface: eth1
          consul_advertise_address: 192.168.33.10
          consul_node_role: server
        vagrant-hashi-stack-2.alpha.consul:
          consul_iface: eth1
          consul_advertise_address: 192.168.33.11
          consul_node_role: client
        vagrant-hashi-stack-3.alpha.consul:
          consul_iface: eth1
          consul_advertise_address: 192.168.33.12
          consul_node_role: client
    nomad_instances:
      hosts:
        vagrant-hashi-stack-1.alpha.consul:
          nomad_node_role: both
        vagrant-hashi-stack-2.alpha.consul:
          nomad_node_role: both
        vagrant-hashi-stack-3.alpha.consul:
          nomad_node_role: both
    vault_instances:
      hosts:
        vagrant-hashi-stack-1.alpha.consul:
        vagrant-hashi-stack-2.alpha.consul:
        vagrant-hashi-stack-3.alpha.consul:
