---
- name: Open nomad ports so that the servers can communicate
  ufw: 
    rule: allow 
    port: "{{ item.port }}" 
    proto: "{{ item.proto }}"
    # src: 
    state: enabled
  with_items:
    - {port: 4646, proto: "tcp"}
    - {port: 4647, proto: "tcp"}
    - {port: 4648, proto: "tcp"}
    - {port: 4648, proto: "udp"}
    