---
vault_datacenter:                               alpha
vault_config_path:                              /etc/vault
vault_cluster_name:                             "{{ vault_datacenter }}"
vault_syslog_enable:                             true
vault_address:                                  0.0.0.0
vault_redirect_addr:                            "{{ inventory_hostname_short }}.alpha.consul"
vault_cluster_address:                          0.0.0.0
vault_iface:                                    eth1
vault_node_name:                                "{{ inventory_hostname_short }}"
vault_group_name:                               vault_instances
vault_user:                                     vault
vault_group:                                    vault

vault_consul:                                   "{{ inventory_hostname_short }}.alpha.consul:8501"
vault_consul_path:                              vault
vault_consul_service:                           vault
vault_consul_protocol:                          https


vault_tls_dir:                                  /etc/ssl/vault
vault_tls_config_path:                          /etc/ssl/vault
vault_tls_disable:                              0
vault_tls_ca_crt:                               cacert.pem
vault_tls_cert_file:                            "{{ inventory_hostname_short }}-vault-server.pem"
vault_tls_key_file:                             "{{ inventory_hostname_short }}-vault-server-key.pem"
vault_tls_cert_file_dest:                       "{{ vault_tls_config_path }}/{{vault_tls_cert_file}}"
vault_tls_key_file_dest:                        "{{ vault_tls_config_path }}/{{vault_tls_key_file}}"
vault_consul_tls_ca_file_dest:                  "{{ vault_tls_config_path }}/{{ vault_tls_ca_crt }}"
validate_certs_during_api_reachable_check:      true