.PHONY: generate-ssh vagrant-node base clean-playbooks docker-install
# NODE_PORT := $(shell vagrant port node --guest 22)
# PRIVATE_KEY := .vagrant/machines/node/virtualbox/private_key
ENVIRONMENT ?= vagrant
PLAYBOOKS := playbooks
INVENTORY := inventories/$(ENVIRONMENT)
# either environment variables or kubestorage
# PROJECT_NAME ?= kubestorage
# ORG_NAME ?= kubestorage
# REPO_NAME ?= kubestorage
#
# DEV_COMPOSE_FILE := docker/dev/docker-compose.yml

# get colors from http://linuxmanage.com/colored-man-pages-log-files.html
YELLOW := "\e[0;33m" # yellow
RED := "\e[0;31m" # Red
NC := "\e[0m"	# no color

INFO := @bash -c '\
	printf $(YELLOW); \
	echo "=> $$1"; \
	printf $(NC)' VALUE

WARN := @bash -c '\
	printf $(RED); \
	echo "=> $$1"; \
	printf $(NC)' VALUE

remove_dangling_images:
	docker images -q -f dangling=true label=application=$(REPO_NAME) | xargs -I ARGS docker rmi -f ARGS

generate-ssh:
	$(INFO) "generating ssh file"
	@mkdir -p .ssh
	@ssh-keygen -t rsa -b 4096 -C "vagrant@vagrant.com" -N "" -f .ssh/id_rsa

create-instances:
	@vagrant up

destroy-instances:
	vagrant destroy -f node

node-ssh:
	ssh -p $(NODE_PORT) -i $(PRIVATE_KEY) vagrant@127.0.0.1

gather-facts:
	@ansible -i hosts all -m setup --tree /tmp/facts

## Ansible commands
ansible-test:
	${INFO} "Testing Ansible connection"
	ansible -i $(INVENTORY) all -m ping

base:
	${INFO} "Running base playbook"
	ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/basic/playbooks/site.yml

hashi-stack:
	${INFO} "Running base playbook"
	ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/hashi-stack.yml

interfaces:
	${INFO} "Running base playbook"
	ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/interfaces.yml

deploy-consul:
	${INFO} "Running playbook to deploy consul"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/consul/playbooks/site.yml

deploy-consul-config:
	${INFO} "Running playbook to deploy consul"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/consul/playbooks/site.yml --tags "config-bootstrap,config-server"

deploy-consul-server-config:
	${INFO} "Running playbook to deploy consul"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/consul/playbooks/site.yml --tags "config-server"

remove-consul:
	${INFO} "Running playbook to remove consul containers"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/consul/playbooks/remove_consul.yml

deploy-vault:
	${INFO} "Running vault deploy playbook"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/vault/playbooks/site.yml

remove-vault:
	${INFO} "Running playbook to remove vault"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/vault/playbooks/remove_vault.yml

deploy-nomad:
	${INFO} "Running nomad deploy playbook"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/nomad/playbooks/site.yml

install-docker:
	${INFO} "Running docker install playbook"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/docker/playbooks/site.yml

copy-nomad-jobs:
	${INFO} "Running nomad deploy playbook"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/nomad-jobs/playbooks/site.yml

deploy-nomad-config:
	${INFO} "Running nomad deploy playbook"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/nomad/playbooks/site.yml --tags "config-server"

remove-nomad:
	${INFO} "Running nomad to remove vault"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/nomad/playbooks/remove_nomad.yml

pristine:
	${INFO} "Running playbook to remove vault"
	@ansible-playbook -i $(INVENTORY) $(PLAYBOOKS)/$(ENVIRONMENT)/pristine/playbooks/main.yml

clean-playbooks:
	${WARN} "Deleting all *.retry files from playbooks directory"
	rm $(PLAYBOOKS)/*.retry

# deploy-minio:
# 	${INFO} "Deploying minio"
# 	ansible-playbook --vault-password-file=kubestorage/.vault_pass -i $(INVENTORY) $(PLAYBOOKS)/deploy_minio_playbook.yml